name: Post Release Job
'on':
  schedule:
    - cron: '* * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "pminz"
          git config --global user.email "pminz@redhat.com"
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: operator
          ref: '${{ env.REF }}'
          token: '${{ secrets.PAT}}'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{ env.REL_VERSION  }}'
        env:
          GITHUB_TOKEN: '${{ secrets.PAT }}'
    env:
      DELAYED_JOB_CHECKOUT_REF: a53d4979244b0584e324a6dddc1ee6c1c2440d1e
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: .github/workflows/publish-main.yaml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: test_crelease
      REF: test_crelease
      REL_VERSION: 2.4.12.Final
